---
title: "US employment tracker"
author: "Carlos Daboin"
format: 
  html:
    toc: true
    code-fold: true
    code-summary: "Show the code"
execute: 
  echo: false
  eval: true 
  warning: false
---

```{r}
# 0.0 Install libraries --------------------------
# This step is automated by the github actions yalm
# One package must be downloaded from github. 
# devtools::install_package("keberwein/blscrapeR")

# 0.1 Load Libraries -----------------------------
library(dplyr)
library(readr)
library(blscrapeR)
library(ggplot2)
library(stringr)
library(gt)
library(lubridate)
options(scipen=999)# to see large numbers without scientific notation

source("functions.R")
```


Report last updated `r Sys.Date()`.

```{r old_data}

bind_old_and_new<-function(old_data="data/df_1_clean.rds",
                           new_data="data/df_1_clean_new.rds"){

data<-read_rds(old_data) %>%
  filter(! (footnotes=="P preliminary" | footnotes=="P Preliminary") )%>%
  rbind(read_rds(new_data) %>%
  filter(footnotes=="P preliminary"|footnotes=="P Preliminary")) %>% 
  arrange(desc(date))
}

# National data
df_1_clean<-bind_old_and_new("data/df_1_clean.rds","data/df_1_clean_new.rds")
df_2_clean<-bind_old_and_new("data/df_2_clean.rds","data/df_2_clean_new.rds")

nat_periods<-tibble('Last period avaliable'=max(df_1_clean$date),
           'Preliminary estimates'=paste(unique(df_1_clean[df_1_clean$footnotes=="P preliminary",]$date),collapse = ", "))

# State data
df_state_1_clean<-read_rds("data/df_state_1_clean.rds")
df_state_2_clean<-read_rds("data/df_state_2_clean.rds")
# df_state_1_clean<-bind_old_and_new("data/df_state_1_clean.rds",
#                                    "data/df_state_1_clean_new.rds")
# df_state_2_clean<-bind_old_and_new("data/df_state_2_clean.rds",
#                                    "data/df_state_2_clean_new.rds")

sta_periods<-tibble('Last period avaliable'=max(df_state_1_clean$date),
           'Preliminary estimates'=paste(unique(df_state_1_clean[df_state_1_clean$footnotes=="P Preliminary",]$date),collapse = ", "))

```

## Nation-level report

```{r}
plots_1<-ces_plots(data=df_1_clean, title_text = "- U.S Total")
plots_2<-ces_plots(data=df_2_clean, title_text = "- U.S Total")
nat_periods %>% 
  gt() %>% 
  gt::tab_header(title="Update status",
                 subtitle = "Nation-level estimates")
```

### By broad sectors
```{r}
plots_1[[1]]

plots_1[[2]]

```


### By detailed sectors
```{r}
plots_2[[1]]

plots_2[[2]]
```

## State-level report

```{r}
sta_periods %>% 
  gt() %>% 
  gt::tab_header(title="Update status",
                 subtitle = "State-level estimates")
```

We first show the broad view, then the detailed one.

#### Work in progress...
* Need to fix the legends.
* Need to add seasonally-adjusted series.
* Will add forecast.

```{r, echo=TRUE}

lista<-list()
for (states in sort(unique(df_state_1_clean$state_title))) {
 
  plots_1<-ces_plots(data=filter(df_state_1_clean,state_title==states), 
                     title_text = paste0("-",states))
  
  plots_2<-ces_plots(data=filter(df_state_2_clean,state_title==states), 
                     title_text = paste0("-",states))
  
lista[[states]]<-  list(plots_1[[2]],plots_2[[2]])
  
}


lista[1:51]

```

