on:
  push:
    branches: new_etl_report

jobs:
  import-data:
    runs-on: ubuntu-latest
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install main packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::readr
            any::dplyr
            any::lubridate
            any::stringr
            any::ggplot2
            any::scales
            any::ggrepel
            any::patchwork
            github::keberwein/blscrapeR  

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run code
        # run: Rscript -e 'source("2023_bls_api_etl.R")'
        run: Rscript -e 'source("0_main.R")'

      - name: Commit results
        env: 
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/*
          git commit -m 'Data and plots' || echo "No changes to commit"
          git push origin || echo "No changes to commit"        